### PR TITLE
Updates to Docker execution

### LINKED ISSUE #432: Standardise Process Execution in `tests/utils/exec.ts`
### Specification

With the resolution of MatrixAI/Polykey#410, there is some messiness left in the `tests/utils/exec.ts`.

We want to standardise the implementation of:

* `pkExec`
* `pkSpawn`
* `pkExpect`

Clarify the behaviour of `pk` and `pkStdio` in the comments.

And also incorporate the requirement of `pkExecNs` and `pkSpawnNs` into the main 3 functions above.

Due to the difference in command and argument quoting behaviour when `shell: true` for `child_process.execFile` (https://github.com/MatrixAI/Polykey/pull/391#issuecomment-1196318536), we should no longer using `child_process.execFile` (and nor are we supposed to use `child_process.exec`).

This means all 3 functions will instead be using `child_process.spawn`.

These functions will need to add an additional option for the command string override. Currently the functions all take existing required parameters, this could be rolled into an options object instead for easier extensibility. The below examples assumes this has been done.

Right now we have a `PK_TEST_COMMAND` which overrides the default `ts-node` command string running against `${globalThis.projectDir}/src/bin/polykey.ts`.

However we want to have the standard override idiom: `PARAMETERS > ENVIRONMENT > DEFAULT`.

This allows us to incorporate `pkExecNs` and `pkSpawnNS` into the same system, as they will be explicitly setting network namespaced command string.

To make this nicer to use, the `exec.ts` should also be exporting:

```ts
const polykeyPath = `${globalThis.projectDir}/src/bin/polykey`

export {
  polykeyPath
};
```

So any usage of `pkExecNs` and `pkSpawnNs` should look like:

```ts
import * as testExec from '../utils/exec';

await pkExec(
  ['agent', 'start'], 
  { command: `${nsenter(usernsPid, netnsPid)} ts-node ${testExec.polykeyPath}}`}
)
```

Now the 3 commands are going to be the entrypoints for executing Polykey. We can still export the target variants (which we've renamed to be explicitly about `WithShell` and `WithoutShell`) in case there are edge cases.

If we need to, it should be like this:

```ts
const polykeyPath = `${globalThis.projectDir}/src/bin/polykey`

// By default `globalThis.testCommand` should be `undefined` because `PK_TEST_COMMAND` will not be set
// This is strictly checking for existence, `PK_TEST_COMMAND=''` is legitimate but undefined behaviour
async function pkExec(args, opts: { command: globalThis.testCommand }) {
  if (opts.command == null) {
    await pkExecWithoutShell(args);
  } else {
    await pkExecWithShell(args, { command });
  }
}

// This is the DEFAULT
async function pkExecWithOutShell(args) {
  await childProcess.spawn(`ts-node ${polykeyPath}`, args, { shell: false });
}

// This is the PARAMETER > ENVIRONMENT override
async function pkExecWithShell(args, opts) {
  args = args.map(escapeShellArg);
  await childProcess.spawn(opts.command, args, { shell: true });
}

function escapeShellArg(arg: string): string {
  return arg.replace(/(["\s'$`\\])/g,'\\$1');
}

export {
  polykeyPath,
  pkExec,
  pkExecWithoutShell,
  pkExecWithShell,
  escapeShellArg,
};
```

This requires that the from the user's (tester's) perspective, the execution behaviour should stay the same. This requires us to sanity check a few things:

1. All signals are propagated from the intermediate shell process to the PK agent process
2. All child process events are received as if the `shell: false` was set

Note the argument escaping function `escapeShellArg`, this is necessary to ensure that any shell metacharacters in the argument strings are interpeted literally.

To make the above work for docker integration tests, we also need to change our `release.nix` to use `Entrypoint` instead of `Cmd`:

```nix
      config = {
        Entrypoint = "/bin/polykey";
      };
```

This will require updates to `Polykey-Infrastructure` as well, as there's no more `/bin/polykey` needed. You can just pass arguments directly after, e.g. `docker run image:tag agent start`.

Finally we are left with:

* `pk` - this just calls the `main` function
* `pkStdio` - this just wraps `pk` with mocking
* `exec` - this is intended to call any other program arbitrarily

The `pk` and `pkStdio` should be reverted to back to how it was before. Except with potentially some signature change to abide by changes to `pkExec` and friends. They are intended to be only for function execution, and not real process testing. If any test needs to do integration testing, they can migrate to using `pkExec` instead. Or a new test can be created that does that specifically.

The `exec` should taking input signature similar to `spawn`, this way it is possible for the end user to also specify `shell: true` and `shell: false` and use `escapeShellArg` for their special cases.

### Additional context

* Because `spawn` returns a process reference, any function expecting simple promise results should wrap the process with any relevant promise handlers.
* https://github.com/MatrixAI/Polykey/pull/391#issuecomment-1196318536 - research on shell behaviour differences
* MatrixAI/Polykey-Simulation#1 - NAT tests is currently incompatible with docker integration tests, they are going to be running independently, this is because NAT tests use a different command string, using namespaces, if NAT tests need to be run in integrated fashion, they can only be applied on the Linux platform with a Linux binary in the `PK_TEST_COMMAND`, if NAT tests need to be run during integration for other platforms, separate tests would have to be written for Docker, MacOS, Windows as they cannot simulate network namespaces (except for docker, but I don't think the CI/CD would be capable of this), so instead they would do this as part of MatrixAI/Polykey-CLI#71 which means going for `testnet.polykey.io` instead of local NAT simulation testing

### Tasks

1. Move `test/utils.ts` into `tests/utils/utils.ts` and create `tests/utils/index.ts`:
   ```ts
   export * from './utils.ts';
   export * as exec from './exec.ts';
   ```
2. Change the `pkExec`, `pkSpawn`, `pkExpect` signatures to taken an options object at the very end, required parameters can be specified as part of object, or as initial parameters
3. Refactor `pkExec`, `pkSpawn`, `pkExpect` according to spec.
4. Remove `pkExecNs` and `pkSpawnNS` and replace with `pkExec` and `pkSpawn` with command override options.
5. Command override options should produce a command string to be used in `spawn(cmd)`.
6. Any usage of `global` should be using `globalThis` instead, this is the correct form way of accessing globals.
   * Incorporate https://eslint.org/docs/latest/rules/no-restricted-globals and ensure that `window` and `global` are not allowed to be used.
7. Export functions in order of precedence (always the functions the users are supposed to be using, and then utilities for edgecases).
8. Change `release.nix` to use `Entrypoint`.
9. Deploy container in CI/CD but also update task definition in `Polykey-Infrastructure`
10. Sanity check signalling and process events when using `shell: true` with the intermediate process, post results of these sanity checks along with code doing the check in this issue for reference.
11. No usages of `execFile` nor `exec` should be used at all.
12. Due to linting rules, `child_process` should actually be `childProcess`, make the necessary changes.

### PR DESCRIPTION
**Pull request by emmacasolin**
### Description

MatrixAI/Polykey#432 is making changes to the way we do process execution, which impacts our docker tests. This requires updating the affected tests, redeploying in the CI/CD, and sanity checks for the expected behaviour.

Related to https://gitlab.com/MatrixAI/Engineering/Polykey/Polykey-Infrastructure/-/merge_requests/1

### Issues Fixed

* Relates MatrixAI/Polykey#432 

### Tasks
- [x] 1. Change `release.nix` to use `Entrypoint` instead of `Cmd`
- [x] 2. Update the task definition in `Polykey-Infrastructure`
- [x] 3. Update all docker tests
- [x] 4. Merge https://gitlab.com/MatrixAI/Engineering/Polykey/Polykey-Infrastructure/-/merge_requests/1
- [x] 5. Redeploy container image and service
- [ ] 6. Sanity checks for signalling and process events
- [x] 7. Update `README` instructions for container/docker usage

### Final checklist

* [ ] Domain specific tests
* [ ] Full tests
* [ ] Updated inline-comment documentation
* [ ] Lint fixed
* [ ] Squash and rebased
* [ ] Sanity check the final build

### CODE REVIEW

**Comment by emmacasolin** [comment]
This is the PR in `Polykey-Infrastructure` for updating the task definition: https://gitlab.com/MatrixAI/Engineering/Polykey/Polykey-Infrastructure/-/merge_requests/1

**Comment by emmacasolin** [comment]
One of the biggest changes coming in from https://github.com/MatrixAI/Polykey/pull/436 is that `pkStdio` is no longer compatible with docker integration tests. This is because the original `pkStdio` was not compatible with these tests since it mocked `stdout` and `stderr`. It was changed to essentially just call `pkExec` underneath when used with docker, however, this functionality is being removed. Any tests that need to run on docker need to switch from using `pkStdio` to using `pkExec`, a change which is being made to existing tests in https://github.com/MatrixAI/Polykey/pull/436 so this just needs to be kept in mind for any future tests we want to add to our suite of docker integration tests.

**Comment by CMCDragonkai** [comment]
> One of the biggest changes coming in from https://github.com/MatrixAI/Polykey/pull/436 is that `pkStdio` is no longer compatible with docker integration tests. This is because the original `pkStdio` was not compatible with these tests since it mocked `stdout` and `stderr`. It was changed to essentially just call `pkExec` underneath when used with docker, however, this functionality is being removed. Any tests that need to run on docker need to switch from using `pkStdio` to using `pkExec`, a change which is being made to existing tests in https://github.com/MatrixAI/Polykey/pull/436 so this just needs to be kept in mind for any future tests we want to add to our suite of docker integration tests.

This is correct. The `pkStdio` should not be used unless the test is expected to never be an integration test. So any test using `pkStdio` should be convert to `pkExec` in this scenario. However with the loss of the ability to mock STDIO we need `pkExpect` to be shell capable so we can do proper stdio expectations. Please link that issue and that will be a subsequent work to do, which may involve forking `nexpect`.

**Comment by CMCDragonkai** [comment]
However we are not replacing the `pkStdio` tests for now. That's assigned to MatrixAI/Polykey-CLI#7.

This should only be affecting existing docker tests by removing the `/bin/polykey`.

**Comment by CMCDragonkai** [comment]
@tegefaulkes can you point out where we need to remove `/bin/polykey` when docker integration tests are run?

**Comment by tegefaulkes** [comment]
`/bin/polykey` needs to be removed from the `PK_TEST_COMMAND` in the gitlab ci file. at `.gitlab-ci.yml:342` `PK_TEST_COMMAND="docker run \$DOCKER_OPTIONS $image_and_tag /bin/polykey" npm run test -- tests/bin;`

**Comment by emmacasolin** [comment]
`PK_TEST_COMMAND` has been updated. This should now be ready for CI/CD redeployment.

**Comment by CMCDragonkai** [comment]
Are the recent job failures the same timeouts as before? Not introduced by this PR?

**Comment by CMCDragonkai** [comment]
Also have you see that the Nat tests are timing out. Can this be fixed up in your testnet tests PR?

**Comment by emmacasolin** [comment]
The failures are all timeouts on tests that usually take very close to the set timeout time to complete, so if they take slightly too long they timeout. They can't be due to this PR since this PR only touches the `integration:docker` job and `release.nix`, neither of which would affect tests during the `check` stage.

There's only one NAT test timing out, and it usually takes close to 40s to run. It doesn't always timeout on the CI/CD but when it does it's most likely just that test taking slightly too long. The only fix would be increasing the timeout or waiting to see if MatrixAI/Polykey#419 causes the test to run any faster.

**Comment by CMCDragonkai** [comment]
Merged on Polykey-Infrastructure. This requires an image build and upload. Image is uploaded here, so until CI/CD is green we have to do this manually.

**Comment by CMCDragonkai** [comment]
Manual deployment done and instructions updated: 7b1edbd6ec77c1a5705563de7a940f7441d1ac53

```
taskDefinition: 'arn:aws:ecs:ap-southeast-2:015248367786:task-definition/polykey-testnet:76',
```

**Comment by CMCDragonkai** [comment]
I've updated the task definition on AWS. And I noticed that the image itself doesn't have a `HOME` which impacts the `NODE_PATH` automatic derivation.

If a `NODE_PATH` and `HOME` doesn't exist, it ends up defaulting to `/.local/share/polykey` (because `os.homeDir()` becomes just `/`).

This is something to be aware of. I also fixed up the path construction to be using `path.join`, so the help page now shows:

```
  -np, --node-path <path>      Path to Node State (default: "/.local/share/polykey", env: PK_NODE_PATH)
```

This should also help MatrixAI/Polykey-CLI#14 and MatrixAI/Polykey-CLI#11

**Comment by CMCDragonkai** [comment]
Service redeployed.

```
  {
      "serviceName": "polykey-testnet",
      "serviceArn": "arn:aws:ecs:ap-southeast-2:015248367786:service/polykey-testnet/polykey-testnet",
      "status": "ACTIVE",
      "deployments": [
          {
              "id": "ecs-svc/9149761156517349517",
              "status": "PRIMARY",
              "rolloutState": "IN_PROGRESS",
              "rolloutStateReason": "ECS deployment ecs-svc/9149761156517349517 in progress."
          },
          {
              "id": "ecs-svc/6135588724958369979",
              "status": "ACTIVE",
              "rolloutState": "IN_PROGRESS",
              "rolloutStateReason": "ECS deployment ecs-svc/6135588724958369979 in progress."
          },
          {
              "id": "ecs-svc/1428782724658529208",
              "status": "ACTIVE",
              "rolloutState": "COMPLETED",
              "rolloutStateReason": "ECS deployment ecs-svc/1428782724658529208 completed."
          }
      ]
  }
```

Now we wait if the new task definition continues to work. @emmacasolin please check in with AWS dashboard and logs tomorrow as you're writing testnet tests to see if it is deployed correctly. The `command` is now set to just set to:

```
            "command": [
                "agent",
                "start",
                "--verbose",
                "--format=json"
            ],
```

And it should be appending to the entrypoint being `/bin/polykey`.

Furthermore commands are changed to:

```
docker run -it polykey-1.0.0:rkl4ma7wbfvsz1wl95gn9rpz865gk2ai --help
```

@tegefaulkes remember to check in to see if docker integration tests are still working as well when you rebase. Specifically in reference to `6.`.

**Pull request merged**
