### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1048174821 for 69342a80708398bbcefae4c616cbb4af2e854e1c

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1048174821

**Comment by CMCDragonkai** [comment]
Test failure in nodes tests https://gitlab.com/MatrixAI/open-source/Polykey/-/jobs/5366423441 @tegefaulkes

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1048268161 for 35080debd198fad17d8ee9cd2d87d8315b86b720

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1048268161

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 1048268161 for 35080debd198fad17d8ee9cd2d87d8315b86b720

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1048268161

**Comment by tegefaulkes** [comment]
> Test failure in nodes tests https://gitlab.com/MatrixAI/open-source/Polykey/-/jobs/5366423441 @tegefaulkes

I haven't seen this one before. But given that the nodegraph is updated after an event, it may be a race condition with us checking before it finishes updating.

**Pull request merged**
