### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1042105916 for 56a6de56f64e0ede3e79d20772ea0e73a0b32017

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1042105916

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1044477323 for 426b5dd50682edc99259ea0a867529777395b1e9

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1044477323

**Comment by CMCDragonkai** [comment]
@amydevs I think you forgot to lintfix the `GitHubProvider.ts`, I've done this now.

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1044480172 for 5b01c9ec0124d9058f321e4c8e80391df8245ce0

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1044480172

**Comment by CMCDragonkai** [comment]
@amydevs there's a test failure in identities: https://gitlab.com/MatrixAI/open-source/Polykey/-/jobs/5342777910 the property test failed, can you check, might have been a regression from the `GitHubProvider`.

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1046992342 for 9f52ca0a84bdc97e128cc870a49639d549473f80

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1046992342

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1047081110 for 479f8b6b6e16aec4cb3f5ec64cefa11e267c407c

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1047081110

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1047101227 for ec8b63fbfe001e20667e713d68f438e9b063156a

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1047101227

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1047179674 for 4cba6af0039d0a5ec415ab6c88993cfeb66be59e

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1047179674

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 1047179674 for 4cba6af0039d0a5ec415ab6c88993cfeb66be59e

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1047179674

**Comment by CMCDragonkai** [comment]
If this wasn't caught https://github.com/MatrixAI/Polykey-CLI/pull/42#issuecomment-1776794054 then we need more tests here.

**Pull request merged**
