### PR TITLE
Fixing the GRPC `toError()` bug with `ErrorValidation`

### PR DESCRIPTION
**Pull request by emmacasolin**
### Description
There is currently a bug with the new `ErrorValidation`, which was brought in as part of the new validation system in #321. Since `ErrorValidation` extends `ErrorPolykey`, but also uses a different constructor, `toError()` is unable to properly construct `ErrorValidation`s when throwing errors. Since we want `ErrorValidation` to be able to be used as both a standard `ErrorPolykey`, but also as a way of joining together multiple `ErrorParse`s into a single error, we need to do something like this:
```
class ErrorValidation extends ErrorPolykey {
  description = '...';
  exitCode = sysexits.DATAERR;
  public errors: Array<ErrorParse>;

  constructor(message, data) {

    if (data.errors != null) {
      let errors = [];
      for (const eData of data.errors) {
        const errorParse = new ErrorParse(eData.message);
        errorParse.keyPath = ...eData.keyPath;
        errors.push(errorParse);
      }
      this.errors = errors;
    }


  }

  static createFromErrors(errors: Array<ErrorParse>): ErrorValidation {
    const message = errors.map((e) => e.message).join('; ');
    const data = {
      errors: errors.map((e) => ({
        message: e.message,
        keyPath: e.keyPath,
        value: e.value.valueOf(),
      })),
    };
    const e = new ErrorValidation(message, data);
    e.errors = errors;
    return e;
    // super(message, data);
    // this.description = 'Input data failed validation';
    // this.exitCode = sysexits.DATAERR;
    // this.errors = errors;
  }
}
```

### Issues Fixed
* Fixes https://github.com/MatrixAI/js-polykey/pull/321#issuecomment-1033215131

### Tasks
1. [x] Fix the constructor inside `ErrorValidation` to match `ErrorPolykey`
2. [x] Add a static method to `ErrorValidation` to deconstruct an array of `ErrorParse`s
3. [x] Tests for both usages of `ErrorValidation`, including with `toError()`

### Final checklist
* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by emmacasolin** [comment]
The bug has been fixed, however there aren't tests for the majority of GRPC handlers that validation errors are handled correctly. This could be added either in this PR or in #311.

**Comment by emmacasolin** [comment]
Lintfixed + all tests passing. I added some tests to check that `toError()` is working correctly with some of the handlers that already have split tests on master. The rest can wait until #311. This is now ready for review/merge.

**Comment by CMCDragonkai** [comment]
This looks good, the only thing is to make the commit message more descriptive. State what you are actually fixing in this case:

```
Fixing `ErrorValidation` serialisation over GRPC by putting `ErrorParse` data into `ErrorValidation.data.errors`
```

Would be more valid..

**Comment by CMCDragonkai** [comment]
After you change the message, proceed to merge.

**Comment by emmacasolin** [comment]
Changed the commit name - merging now.

**Pull request merged**
