### PR TITLE
feat: converting to nix flakes

### PR DESCRIPTION
**Pull request by tegefaulkes**
### Description

This PR converts `Polykey` to use the nix flakes system.

### Tasks

- [X] 1. remove old `nix-shell` related files and references.
- [X] 2. create a `flake.nix` file and add all the required native dependencies and code.
- [X] 3. Update all of the CI definitions to use `nix develop` to run commands in the proper environment

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by tegefaulkes** [comment]
@brynblack do you want to have a look over this and check that I haven't missed anything dumb?

**Comment by tegefaulkes** [comment]
I'm going to merge this in after some quick checks. This will enable flakes so we need to use `nix develop` to develop from now on.

**Comment by CMCDragonkai** [comment]
Make sure to compare with Polykey CLI's usage of this. Last time there was a problem - all development environment and testing and CI should be working.

**Comment by tegefaulkes** [comment]
I'm pretty much mirroring how it's done in Polykey-CLI and `js-exec`. so it *should* be working but I'll keep and eye on it and fix any problems quick.

**Pull request merged**
