### PR TITLE
Swapping to SWC, Updating to M1 MacOS, and updating dependencies

### LINKED ISSUE #528: Update MacOS GitLab CI/CD configuration by 31st May
The beta macos machines will be deprecated by 31st May and from then it will be running on the M1 architecture, and will require us to have premium subscription to GitLab again.

See: 

* https://github.com/MatrixAI/js-quic/issues/7#issuecomment-1551451917
* https://gitlab.com/gitlab-com/runner-saas-macos-access-requests/-/issues/233#note_1394334519

Note that if we were to go towards full cross-compilation we may avoid this. But since we have other code like js-db and later that may still use node-gyp we're going to need it anyway.

Do note that M1 and x64 macos is capable of cross compiling architectures. We don't bother with the universal binary cause it's not needed, we are able to publish separate optional packages atm. That way `lipo` is avoided. That does mean though... when distributing PK, we have to distribute an M1 version and a x64 version. The x64 versions are likely to be deprecated in the following years.

### Tasks

- [x] 1. Use `saas-macos-medium-m1` as the tag.
- [x] 2. Use `macos-12-xcode-14` as the image.
- [x] 3. Make sure to update the `systeminformation` to `5.18.5` if it is being used in benchmarking
- [ ] 4. Test that build still works fine on M1

### PR DESCRIPTION
**Pull request by CMCDragonkai**
### Description

This PR is for switching to using `@swc/jest`.

I think this was a dangling branch, but has a change that we want to make use of now that everything is now using `swc`.

However there are some things in this change that still need testing like the removal of jose and babel-jest.

### Issues Fixed

* Related #430 
* Fixes #528

### Tasks

- [x] 1. Update all MatrixAI dependencies to the latest that has been released
- [ ] 2. Test swc tests work
- [ ] 3. Remove or simplify tests that are not required

### Final checklist

* [ ] Domain specific tests
* [ ] Full tests
* [ ] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [ ] Sanity check the final build

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
@tegefaulkes this should be merged first... after completing the tasks.

**Comment by CMCDragonkai** [comment]
The SWC may still have some weird decorator problem but we don't actually use it, so if we have a test for that, we can just disable for those.

This PR can be used to sort out #528 too.

Although atm due to problems compiling js-quic on Windows, we may have some problems releasing a build for Windows.

At any case we will focus on just Linux for now.

**Comment by CMCDragonkai** [comment]
@tegefaulkes focus on this one first. Get the SWC into it, and update all relevant dependencies before `js-quic`. Then merge this into staging.

Then in #525, you can rebase that on top of this and bring in the 0.0.10 js-quic and start integrating that.

We will then address #268 and move all the of the CLI related things to Polykey-CLI so we can get the CI/CD to pass here since the pkg has problems building with the latest nodejs and we can focus in on packing and bundling in Polykey-CLI.

**Comment by tegefaulkes** [comment]
I'm going to leave updating dependencies to later. They include breaking API changes and I'd rather have fixes included in the the commit. But at the same time I don't want to re-base on top of any fixes that need to be done.

**Comment by CMCDragonkai** [comment]
The only breaking change should be the js-db and js-async-locks when it comes to timeouts...

**Comment by CMCDragonkai** [comment]
Also this will break the CI build due to https://github.com/MatrixAI/TypeScript-Demo-Lib/pull/94#issuecomment-1611154454.

We have to accept the breaking for now until all CLI stuff moves to Polykey-CLI.

**Comment by tegefaulkes** [comment]
I can't fully tests things are working since the state of the staging branch is between the client and agent migration. I'll have to do any testing and fixes in the agent migration branch after rebasing it on top of this.

**Comment by CMCDragonkai** [comment]
Yes that's fine, it just has to be merged to staging, you should do some sanity check though.

**Comment by tegefaulkes** [comment]
Alright, I'm merging this now. given the incomplete state of staging I can't run any tests to fully check if all the changes work. That will be done in #525 after rebasing it.

**Pull request merged**
