### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1090256299 for 8f606e5affe141771dd54ca82406d914262c8962

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1090256299

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 1090256299 for 8f606e5affe141771dd54ca82406d914262c8962

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1090256299

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1094109752 for 28f000154403358eb9d5a703afab3359144b5422

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1094109752

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1094115044 for e3d99916b917860c8532b0c080c9878e9d06b544

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1094115044

**Comment by CMCDragonkai** [comment]
This has conflicts with master? How did this happen @amydevs? This requires a force push from staging to master... what was the spurious commit?

**Comment by CMCDragonkai** [comment]
@amydevs don't checkout master and do a separate release, that's not correct. Staging branch should have the release commit, then we fast forward merge into master.

**Comment by CMCDragonkai** [comment]
To fix this, it will require force pushing over master... PITA.

**Pull request merged**
