### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 962916672 for 75df9179828edb7262d0e848663cf06467f5876d

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/962916672

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 962982993 for 7c56b5a7aeb06168565ab6da4f385ecc97f5144b

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/962982993

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 962982985 for 6753e65f6a64efcd28502790c75bf98a70004c6f

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/962982985

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 962982993 for 7c56b5a7aeb06168565ab6da4f385ecc97f5144b

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/962982993

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 967804107 for 4c02f7a287147e89a9add23492a2c492781c023e

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/967804107

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 969073117 for a4443c72ee31f5cb63940872667b594a0be9d5a9

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/969073117

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 969073117 for a4443c72ee31f5cb63940872667b594a0be9d5a9

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/969073117

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 971905600 for d16f6013b23263c0e3c95c5ed1ebdfe032b6e3d0

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/971905600

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 971917641 for 6fc7b80332971f3afdfd138c41ae02f0e169fcc4

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/971917641

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 972359705 for 002533639b43dfb10fa34167143e2a29f5bbffc7

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/972359705

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 972359705 for 002533639b43dfb10fa34167143e2a29f5bbffc7

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/972359705

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1006485084 for 8dd41f72ad377c90a6c2dab2b1371f9eb39a461d

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1006485084

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1025020649 for 9d3641678760e3ca9d4032370da92df6fade98dd

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1025020649

**Comment by CMCDragonkai** [comment]
@tegefaulkes do you notice that there is alot of branch conflicts between staging and master.

image

Where did this all come from?

**Comment by CMCDragonkai** [comment]
I rebased staging on top of master. And there's a change in the number of commits.

```
»» ~/Projects/Polykey
 ♖ git status                                                                (staging) pts/3 6:34:44
On branch staging
Your branch and 'origin/staging' have diverged,
and have 110 and 106 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```

During the rebase I just kept using `git checkout --theirs` to prefer the current `staging` version of chnages over master.

Somebody has been making changes to staging and at one point de-synced from master.

This could only have been possible if some changes were pushed to master, but never done on staging.

Very bad! I don't understand how this could have happened, but I'm likely to disable master/staging maintainer permissions for everybody to prevent this from happening in the future.

**Comment by CMCDragonkai** [comment]
I'm not sure if I can even push up the rebased code. In the new rebased code, there's 4 errors in `NodeConnection.ts` and 9+ errors in `NodeConnectionManager.ts`.

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1025953669 for dda31f5a9f56121d0384f43f8784b815fa1588f8

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1025953669

**Comment by CMCDragonkai** [comment]
I've pushed the rebased staging onto `feature-staging-conflict`. You can see that there is src failures there.

**Comment by CMCDragonkai** [comment]
Forced pushed over this, apparently no difference.

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1025982350 for e39a88cf3e782f7f9c4bfc5147dc869dbb52cf72

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1025982350

**Comment by CMCDragonkai** [comment]
Ok I just compared my rebased version vs the original one with all the conflicts. The rebased one is the same except in 2 cases.

Changes to `src/websockets/WebSocketServer.ts` and `tests/websockets/WebSocket.test.ts`.

So this has 179 files changes, the original only has 177 files changes.

Since we are replacing ws in #560, I'm going to accept this one as the correct one.

**Comment by CMCDragonkai** [comment]
From now on, no more linting commits that is done while there's another downstream PR depending on this PR. That creates whole-project changes that will result in conflicts.

Linting commits can only be done at the tip of all PR stacks.

Alternatively lint every single commit you push up.

Only one of the 2 things should be done.

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1031558225 for 305850725573030c68ba5177c6d3bdeb97cfa257

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1031558225

**Comment by CMCDragonkai** [comment]
It's time to to get this staging passing CI to merge to master.

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1031571973 for d238645c61a7299455c4d42dea6fd7700f128328

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1031571973

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1031659123 for 9622889ea68ac0bcbc28972f57740dba22391244

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1031659123

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 1031659123 for 9622889ea68ac0bcbc28972f57740dba22391244

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1031659123

**Pull request merged**
